### ISSUE TITLE
No ny_metropolitan.kml given as default

### ISSUE THREAD

**Issue by ssivakorn** [nettrino/LBSProximityAuditor#2]
"No such file" exit, when files/data/ny_metropolitan.kml not given. Raised from auditor_discovery_attack.py and libs/kmlparse.py.

Need sample file, by default: files/data/ny_metropolitan.kml??

**Comment by ssivakorn** [comment]
first run will generate only directory:
1. files
2. files/json
3. files/kml
no files/data found.

**Comment by nettrino** [comment]
Thanks! Data file was added in latest push.
